# Generated by Django 6.0.3 on 2026-04-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling_time', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingTimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=100)),
                ('target_date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling_time.account')),
            ],
        ),
    ]
