# Generated by Django 6.0.3 on 2026-04-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling_time', '0002_handlingtimeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='handlingtimeconfig',
            name='offer_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
