# Generated by Django 6.0.3 on 2026-04-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling_time', '0003_alter_account_name_alter_handlingtimeconfig_offer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingtimeconfig',
            name='target_date',
            field=models.DateField(),
        ),
    ]
